### ISSUE TITLE
[lib] Make the default `dtype` of NDArray as `DType.float64`

### ISSUE THREAD

**Issue by forFudan** [Mojo-Numerics-and-Algorithms-group/NuMojo#82]
Currently, the default data type of a `NDArray` is `DType.float32`. This is somehow different from numpy which uses float64 as default type. For example, [numpy.ones()](https://numpy.org/doc/stable/reference/generated/numpy.ones.html).

I am wondering whether it would be nice to change the default data type of `NDArray` from `float32` to `float64` also for numojo, so that it is aligned with numpy and is of higher precision.

I do not think it is a top priority but we can have an open discussion on this.

**Comment by shivasankarka** [comment]
@forFudan We could do that, I don't see any problem with it. Initially, I set it as `DType.float32` to match PyTorch.

**Comment by mmenendezg** [comment]
Is there any potential performance cost on this change?

**Comment by forFudan** [comment]
> Is there any potential performance cost on this change?

The Float64 takes double memory space for higher precision.
