### ISSUE TITLE
Make `sort()` method an inplace method

### ISSUE THREAD

**Issue by mmenendezg** [Mojo-Numerics-and-Algorithms-group/NuMojo#87]
I would like to know if possible to change the behavior of `sort()` in an array to make it an inplace method.

The expected behavior would be like:
```
var array = nm.NDArray[nm.i64](List[Int64](8, 3, 5, 7, 2, 1, 4, 6), shape=List[Int](8))
array.sort()
print(array)

[Output]: 
[	1	2	3	...	6	7	8	]
Shape: [8]  DType: int64
```

I understand that there are times when you don't want to change the original array and the intention is to create a new array, but renaming the current `sort()` to `sorted()` may be an option. 

Let me know what you think

**Comment by shivasankarka** [comment]
@mmenendezg Thank you for the suggestion. We were planning to make this change to make it compatible with numpy where it's usually sorted inplace. What do you think about something like this, 
```
import numojo as nj
var arr = nj.NDArray(3,3)
arr.sorted() # sorts the array in place
var arr_sort = nj.sort(arr) # returns a new sorted array
```

**Comment by mmenendezg** [comment]
I think it makes sense to have the method in the `NDArray` that sorts inplace and one function that returns a copy of an array. 

I was checking the Numpy documentation and I see that the `ndarray` method is called `sort()`. I think keeping the names will improve the adoption.

**Comment by shivasankarka** [comment]
@mmenendezg Agreed! It's better to keep the same naming convention. I have made these changes and I will push it today.

**Comment by shivasankarka** [comment]
Sort method has been changed to match the discussion above in this PR #91.
