### ISSUE TITLE
Error using slices 

### ISSUE THREAD

**Issue by sandstromviktor** [Mojo-Numerics-and-Algorithms-group/NuMojo#93]
Dear all. Thanks for creating NuMojo. I have some issues, and perhaps this is just due to the early stage of this project, but i'll submit this anyway. 

**Describe the bug**
All array operations involving slices seem to fail. 

**To Reproduce**
```python
import numojo as nm


def main():
    var A = nm.NDArray[nm.f64](shape=List[Int](3,3), random=True)

    # These work as expected
    print(A.mean())
    print(nm.math.stats.meanall(A))
    print(nm.math.stats.sumall(A))
    print(A.cumsum())
    
    # All these operations throw the same error
    #nm.math.stats.min(A) # Does not work
    #nm.math.stats.prod(A,axis=0) # Does not work
    #nm.math.stats.sum(A, axis=0) # Does not work
    #A.sum(axis=0) # Does not work
    #nm.math.stats.mean(A) # Does not work
```
and the resulting error message is this

```bash
/NuMojo/numojo/core/ndarray.mojo:1341:9: error: @stdlib::@builtin::@builtin_slice::@Slice::@"__copyinit__(stdlib::builtin::builtin_slice::Slice=&,stdlib::builtin::builtin_slice::Slice)_thunk" does not reference a KGEN declaration
mojo: error: failed to run the pass manager
```

**Expected behavior**
Being able to calculate mean along a given axis, fetching elements using slices etc. 

**Desktop (please complete the following information):**
 - OS: MacOS 14.6.1
 - Latest Mojo version
 - VSCode

**Comment by sandstromviktor** [comment]
Hi and thanks for you reply. I'm running `mojo 24.4.0 (59977802)` using a Macbook Pro M3. 

I've been searching for a solution, and
1.  it works in a ubuntu container where I installed Mojo and NuMojo manually. 
2. I've tried to reinstall Mojo on my machine from scratch. This did not help unfortunately.

**Comment by shivasankarka** [comment]
@sandstromviktor Thank you for using NuMojo and reporting the bug. This is a bug I have experienced specifically for any operations related to slicing. Unfortunately, It is due to the limitations in Mojo packaging currently (.mojopkg doesn't support many operations), I hope modular will improve it in upcoming releases so that we can directly use the .mojopkg instead of importing whole codebase.

**Comment by MadAlex1997** [comment]
Ok interesting, it is a packaging issue.
