### ISSUE TITLE
Merge NDArray inits with fill and random

### ISSUE THREAD

**Issue by MadAlex1997** [Mojo-Numerics-and-Algorithms-group/NuMojo#96]
To reduce the number of initializer overloads for ndarray we could take the `__inits__` that are identical other than having either random or fill and make initializers that default to filling with zeros, and do not allow for the fill to be nonzero if the random argument is true.

```mojo
fn __init__( inout self, *shape: Int, random: Bool = False, order: String = "C" ) raises:
```
and
```mojo
fn __init__( inout self, *shape: Int, fill: Scalar[dtype], order: String = "C" ) raises:
```
becomes 
```mojo
fn __init__( inout self, *shape: Int, fill: Scalar[dtype]=0, random:Bool=False, order: String = "C" ) raises:
    if random == True and fill !=0:
        raise Error("numojo/core/ndarray:NDArray: __init__(*shape, fill, random)): Error if random is true you cannot set a fill value")
```

This would turn 8 of our initializers into 4 thus reducing our number of initializers from 14 to 10.

Thoughts?

**Comment by MadAlex1997** [comment]
PR #97 to the experimental branch implements this.

**Comment by sandstromviktor** [comment]
I would suggest that the `random` argument should be removed completely from this way of creating arrays as it is not obvious that this is uniform distribution between 0 and 1. 
Creating random arrays should be done using `nm.core.random.<some-random-function>`. This would make is explicit what kind of random is being created and allow for parameters to be set, like `nm.core.random.randn(mean=1.0, std=2.0)` or `nm.core.random.randint(min=10, max=100)` etc etc. 
What do you think @MadAlex1997 ?

**Comment by MadAlex1997** [comment]
@sandstromviktor It would be better aligned with NumPy that way. Admittedly most of the data structure and initialization stuff was @forFudan and @shivasankarka, I have handled the math and numerics backend part more. Perhaps they would be able to give their reasoning for it being that way?

The randomly generated scalar/array part of NuMojo is currently pretty limited maybe we could put that on the list for V0.3 along with the many changes for the upgrade to Mojo 24.5.

**Comment by shivasankarka** [comment]
@sandstromviktor  I agree with that. Initially we added it to default constructors as mojo `random` module is quite limited. I am implementing some functions for random number generators right now. I will move these random array constructors to that. 

@MadAlex1997 what other changes do you have in mind for the randomly generated arrays for NuMojo v0.3?

**Comment by shivasankarka** [comment]
I have created a PR #98  with some basic changes for the `random` and `ndarray` module. If you all have any suggestions to improve the random module, please share here or in the PR. Thanks!

**Comment by forFudan** [comment]
@sandstromviktor Your suggestion is nice.

@MadAlex1997 @shivasankarka, Another reason why we did not have a better `random` module was that the built-in `random` module is imported by default (which is actually a known issue https://github.com/modularml/mojo/issues/2529). This leaking polluted the naming space and caused importing `random` from `numojo` to fail in many cases.

With this issue fixed, we can improve the `random` module soon.
